name: Blockchain FE/BE part of Analysis
description: Please fill a frontend/backend part of a blockchain analysis
title: "[FE/BE]: "
labels: ["fe/be"]
assignees:
  - Mskalba
body:
  - type: markdown
    attributes:
      value: |
        Take care of frontend / backend section.
  - type: input
    id: fe-be-section
    attributes:
      label: Link to section
      description: Please provide a link to section
    validations:
      required: true
