name: Blockchain infrastructure part of Analysis
description: Please fill a infrastructure part of a blockchain analysis
title: "[INFRA]: "
labels: ["infrastructure"]
assignees:
  - jchilkie
body:
  - type: markdown
    attributes:
      value: |
        Take care of infrastructure section.
  - type: input
    id: infra-section
    attributes:
      label: Link to section
      description: Please provide a link to section
    validations:
      required: true
